### ISSUE TITLE
Quartz.CoreGraphics Issue

### ISSUE THREAD

**Issue by damonp** [philroberts/FPDB-for-OSX#1]
Hi

I stumbled across your package while trying to get the HUD working on the main package.  

Googling the quartz error, led me to upgrade Python (from Macports), saying 2.6+ fixed the Quartz.CoreGraphics issue.  

But still getting the same errors, on both your's and the main branch.

I see you are still using the Quartz.CoreGraphics includes, so you must have worked around it somehow.  

Any idea what I am doing wrong?

Thanks

```
damonp@neptune:~ $  
Python 2.7...
GuiStove not found. If you want to use it please install pypoker-eval.
Logfile is /Users/damonp/.fpdb/log/fpdb-log.txt
Connected to SQLite: /Users/damonp/.fpdb/database/fpdb.db3
Note: error output is being diverted to /Users/damonp/.fpdb/log. Any major error will be reported there _only_.
opening pipe to HUD
Traceback (most recent call last):
  File "/Users/damonp/fpdb/pyfpdb/HUD_main.pyw", line 54, in <module>
    import OSXTables as Tables
  File "/Users/damonp/fpdb/pyfpdb/OSXTables.py", line 35, in <module>
    from Quartz.CoreGraphics import *
ImportError: No module named Quartz.CoreGraphics
fpdb_import: sending hand to hud 10267 pipe = <subprocess.Popen object at 0x10591d690>
importer    : ERROR    Failed to send hand to HUD: [Errno 32] Broken pipe
fpdb_import: sending hand to hud 10268 pipe = <subprocess.Popen object at 0x10591d690>
importer    : ERROR    Failed to send hand to HUD: [Errno 32] Broken pipe
fpdb_import: sending hand to hud 10269 pipe = <subprocess.Popen object at 0x10591d690>
importer    : ERROR    Failed to send hand to HUD: [Errno 32] Broken pipe
fpdb_import: sending hand to hud 10270 pipe = <subprocess.Popen object at 0x10591d690>
```

**Comment by philroberts** [comment]
Hmm, I don't recall having this issue.  FYI I'm running python 2.6.7 from macports on OSX 10.6.

> simon:~ phil$ python
> Python 2.6.7 (r267:88850, Nov 21 2011, 14:59:21) 
> [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from Quartz.CoreGraphics import *

A theory: what version of python do you get when you run 'python' on the command line?  Because that's the one that will be used to run the HUD process, no matter what you started the main program with.

**Comment by Remcat** [comment]
Hey Phil, having this same issue. Running python 2.7.9. Do I need to go back to 2.6.*?

```
Traceback (most recent call last):
  File "/Users/rabdelaz/FPDB-for-OSX/pyfpdb/HUD_main.pyw", line 64, in <module>
    import OSXTables as Tables
  File "/Users/rabdelaz/FPDB-for-OSX/pyfpdb/OSXTables.py", line 35, in <module>
    from Quartz.CoreGraphics import (CGWindowListCreate,
ImportError: No module named Quartz.CoreGraphics
```

I just installed pyobjc using easy_install but i'm still getting this error.

**Comment by philroberts** [comment]
Some guesswork: easy_install might not be the easy_install for your python.  On my machine:

```
phil$ which python
/opt/local/bin/python
```

```
phil$ which easy_install
/usr/bin/easy_install
```

If you insist on using easy_install this might help:

```
phil$ which easy_install-2.7
/opt/local/bin/easy_install-2.7
```
