### ISSUE TITLE
Crash in hand viewer when clicking checkbox All

### ISSUE THREAD

**Issue by andersea** [philroberts/FPDB-for-OSX#10]
When I go into the menu Cash->Hand viewer and go down to the bottom left of the list of all possible hands and click the All check box, the fpdb closes immediately. No warnings or error messages, but I assume it crashes.

I am using 0.41.0-rc7 for Windows from this link:

https://github.com/philroberts/FPDB-for-OSX/releases/download/0.41.0-rc7/fpdb-win-0.41.0-rc7.zip

**Comment by philroberts** [comment]
Ah yes, I think this is the thing I fixed here a749b52ebf5aa8df66c62a217b0d9ca8e9726346.  As noted there, it doesn't (and never did) do anything useful anyway.
