### ISSUE TITLE
Individual HUD Statistics windows can appear behind the table windows

### ISSUE THREAD

**Issue by andersea** [philroberts/FPDB-for-OSX#12]
I am using the Danskespil.dk client for Bwin/PartyPoker network.

Here the hud has found the right window to attach to, but the individual stats window lie bellow the table in the window stack.

![Screenshot of individual stats windows in the process bar](http://i.imgur.com/FnCqn6g.png)

You can click on each window individually from the process bar at the bottom and click them up in front of the poker table window, but as soon as you click the table, the statistics windows go back behind the table window.

![Screenshot of table window with a couple of stats windows clicked to the front](http://i.imgur.com/gsdG0YB.png)

**Comment by philroberts** [comment]
I've seen this before.  Setting the fpdb and HUD_main exe's to run as administrator might help.

**Comment by andersea** [comment]
I will test it. Thanks.

**Comment by andersea** [comment]
I haven't had this happen after I set run as administrator.
