### ISSUE TITLE
mucked module gaining table focus

### ISSUE THREAD

**Issue by mnabakker** [philroberts/FPDB-for-OSX#17]
The 'mucked' aux module, will force it's table 'top window' when the cards are displayed.
This might or not be intentional, but has gotten me by surprise more then once.
I have been removing the 'mucked' aux module from the games i play for some time...

Windows 7 x64 ENG
FPDB 41 rc8
pokerstars.fr ENG

**Comment by philroberts** [comment]
I recall being annoyed by this as well when I was testing it, but I don't usually use it so I just turned it back off again and forgot about it.  I actually can't remember if I ever tried to resolve the issue or just turned it off and put it in the 'maybe later' pile.

I also don't remember if this happened in 0.40.5 - if it didn't there's a stronger argument for trying to fix it, given I apparently made it so.

I'll do a bit of digging when I find time.  Is this a big deal for you?

**Comment by mnabakker** [comment]
This is the case in 40.5 also, for me there is no real need.
It is like you said, annoying. but activated by default....

**Comment by philroberts** [comment]
OK, presumably I gave up on trying to 'fix' it if that was the existing behaviour anyway.  Who knows, maybe if I found a way to change it someone would complain that it stopped working the way they like.

Closing the issue for now, but I'll put a note in my 'things to do' for FPDB and maybe try to figure it out at some point.
