### ISSUE TITLE
zoom pokerstars

### ISSUE THREAD

**Issue by pashinki** [philroberts/FPDB-for-OSX#56]
Hi, 
in pokerstars zoom , the hud does not show up. Even though i can see entries in fpdb in autoimport column.

**Comment by philroberts** [comment]
Correct, the HUD can't work with zoom.  The HUD gets seating information from the hand history, which only appears after the hand is complete.  On zoom tables this means you never know the current hand's players.  (On regular tables this is also true, but most of the time the current hand's players are the same as the previous hand so it works out.)

**Comment by pashinki** [comment]
Is there no other way pull up the current players?

**Comment by philroberts** [comment]
Not as currently implemented, no.
