### ISSUE TITLE
41.0-rc6 not opening on Windows

### ISSUE THREAD

**Issue by ghost** [philroberts/FPDB-for-OSX#7]
I'm not even really sure where to begin, but the application won't open on my Windows 10 machine now. It used to work fine, but then I tried unchecking PokerStars from the preferences, and it said I needed to restart the program because windows were open. So I closed it and reopened it. But now when opening fpdb application the window appears for half a second then just disappears.

I tried deleting the fpdb folder but the same thing just happens with a fresh download. Not sure how helpful that is, but I'm not even sure where to begin. Any help is appreciated.

**Comment by philroberts** [comment]
I replied in the 2+2 thread.  TL;DR the config file probably got into an unhealthy state.  It should be in %appdata%\fpdb - delete HUD_config.xml from that folder or even delete the whole folder, and try running again.

**Comment by ghost** [comment]
Deleting the config file worked. Thanks!
