### ISSUE TITLE
HandsViewer closing on checkbox

### ISSUE THREAD

**Issue by elprobes** [philroberts/FPDB-for-OSX#8]
Hi man, thanks for awesome work. I use fpdb windows version through wine (you helped me to set up it on irc channel. I use ubuntu 14.04). Everything is working fine except that when i click on every of the 3 checkbox on the bottom (all, suited, off) it suddenly close and i need to restart. Thanks

P.S.
btw none of the cards button does a thing but maybe they are not coded yet
P.P.S.
maybe it's only because i use FPDB through wine xD

**Comment by philroberts** [comment]
Thanks for the report.  Those checkboxes were incorrectly connected to the function that handles them, however it never did anything anyway so I never tested it too much.  On my OSX install it doesn't crash but it doesn't do anything useful either.  Fixed the bug in my local copy, so hopefully will no longer crash, but still won't do anything.  :)

The individual card buttons _should_ work to filter corresponding hands in hold'em.  By default they are all toggled on, so clicking one should remove all instances of that hand from the hand viewer list.
