### ISSUE TITLE
HUD problem on Partypoker tournament

### ISSUE THREAD

**Issue by Mattiews** [philroberts/FPDB-for-OSX#9]
Hi,

HUD does not work from the blind level 500/1'000, the hands are no longer imported.

Is there a problem with the thousand separator that appears at this point ? 

Here are the error messages :

2016-01-31 18:04:05,543 parser ERROR   PartyPokerToFpdb.determineGameType: '#Game No : 15032862787
   ****\* Hand History for Game 15032862787 *****
   NL Texas Hold'em $1.10 USD Buy-in Trny:122579534 Level:16  Blinds-Antes(500/1'000 -100) - Sunday, January 31, 18:03:02 CET 2016
   Ta'
2016-01-31 18:04:05,543 parser ERROR   FpdbParseError for file 'c:\Programs\PartyGaming\PartyPoker\HandHistory\Mattiews\20160131\$500 Gtd 6Max Turbo Rebuy (122579534) Table #14.txt'

**Comment by philroberts** [comment]
I think you have correctly diagnosed the issue.  What the heck kind of thousands separator is that?  Is there any way you can convince it to use a comma or period?  Otherwise I can just add it to the parser, I guess.

**Comment by Mattiews** [comment]
Thanks for your prompt answer.

I think it's rather a single quote (') for the blind level but a comma for stack players. Here is an example of my hand history file. It would be great if you could solve it.

#Game No : 15032870678 
****\* Hand History for Game 15032870678 *****
NL Texas Hold'em $1.10 USD Buy-in Trny:122579534 Level:16  Blinds-Antes(500/1'000 -100) - Sunday, January 31, 18:05:53 CET 2016
Table $500 Gtd 6Max Turbo Rebuy (122579534) Table #14 (Real Money)
Seat 1 is the button
Total number of players : 4/6 
Seat 3: hero ( 13,859 )
Seat 4: player4 ( 10,428 )
Seat 6: player6 ( 21,753 )
Seat 1: player1 ( 52,104 )
Trny:122579534 Level:16 
Blinds-Antes(500/1'000 -100)
player1 posts ante [100]
hero posts ante [100]
player4 posts ante [100]
player6 posts ante [100]
player3 posts small blind [500].
player4 posts big blind [1,000].
*\* Dealing down cards **
Dealt to hero [  Kd 3d ]
player6 folds
player1 is all-In  [52,004]
hero folds
player4 folds
player1 does not show cards.
player1 wins 53,904 chips
Game #15032871276 starts.

**Comment by philroberts** [comment]
It's not even used consistently?  This is so much fun.  OK, I will add it to the parser, thanks for the report.

**Comment by Mattiews** [comment]
Yeah that's true and maybe other rooms are also using this process.

Thanks for your loyalty.

**Comment by philroberts** [comment]
Committed the fix locally, will be included in next release.
